gems:
  - jekyll-paginate
  - jekyll-gist

# Site settings
title: String Labs
email: gustav.simonsson@gmail.com
description: "string labs"
github_username: string-labs

# Build settings
markdown: kramdown
kramdown:
  input: GFM
# GFM = GitHub Flavored Markdown
highlighter: rouge

permalink: pretty

# Serve settings
host: 0.0.0.0

paginate: 5
paginate_path: "/news/page-:num/"
# Build settings
authors:
    dominicw:
        display_name: Dom Williams
        email: dominic@string.technology
        twitter: dominic_w
        avatar: dom-head2.jpg

    Dom Williams:
        display_name: Dom Williams
        email: dominic@string.technology
        twitter: dominic_w
        avatar: dom-head2.jpg
    Tom Ding:
        display_name: Tom Ding
        email: tom@lostdecadegames.com
        twitter: tom_ding
        avatar: tom-head2.jpg  


