# Site settings
title: String Labs
email: gustav.simonsson@gmail.com
description: "string labs"
github_username: string-labs

# Build settings
markdown: kramdown
permalink: pretty

# Serve settings
host: 0.0.0.0


relative_permalinks: false
